import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import { Suspense } from "react";
import Loading from "./loading";
import { cookies } from "next/dist/client/components/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NextJS 학습 공간",
  description: "Generated by create next app",
};

const theme = cookies().get("theme");

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <Script src="https://cdn.iamport.kr/v1/iamport.js" />
      <body className={inter.className}>
        <button>123</button>
        <Suspense fallback={<Loading />}>{children}</Suspense>
      </body>
    </html>
  );
}
