import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import { Suspense } from "react";
import Loading from "./loading";
import { cookies } from "next/dist/client/components/headers";
import ThemeButton from "@/components/utils/ThemeButton";
import { Theme } from "@/types";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NextJS 학습 공간",
  description: "Generated by create next app",
};

const theme = cookies().get("theme");
const curTheme =
  cookies().get("theme")?.value === "dark" ? Theme.dark : Theme.light;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={theme?.value} suppressHydrationWarning>
      <head />
      <Script src="https://cdn.iamport.kr/v1/iamport.js" />
      <body className={inter.className + "relative"}>
        <nav className="fixed top-7 right-10 z-50">
          <ThemeButton theme={curTheme} />
        </nav>
        <Suspense fallback={<Loading />}>{children}</Suspense>
      </body>
    </html>
  );
}
